apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudwatch-exporter-config
  namespace: monitoring
data:
  config.yml: |
    region: ap-northeast-2
    metrics:
      - aws_namespace: AWS/EKS
        aws_metric_name: CPUUtilization
        aws_dimensions: [ClusterName]
        aws_dimension_select:
          ClusterName: [hippo-eks-dev]
        aws_statistics: [Average]
        period_seconds: 300
        range_seconds: 600
        delay_seconds: 300
        set_timestamp: true
      - aws_namespace: AWS/EKS
        aws_metric_name: MemoryUtilization
        aws_dimensions: [ClusterName]
        aws_dimension_select:
          ClusterName: [hippo-eks-dev]
        aws_statistics: [Average]
        period_seconds: 300
        range_seconds: 600
        delay_seconds: 300
        set_timestamp: true
      - aws_namespace: AWS/ApplicationELB
        aws_metric_name: RequestCount
        aws_dimensions: [LoadBalancer]
        aws_statistics: [Sum]
        period_seconds: 300
        range_seconds: 600
        delay_seconds: 300
        set_timestamp: true
      - aws_namespace: AWS/ApplicationELB
        aws_metric_name: TargetResponseTime
        aws_dimensions: [LoadBalancer]
        aws_statistics: [Average]
        period_seconds: 300
        range_seconds: 600
        delay_seconds: 300
        set_timestamp: true
      - aws_namespace: AWS/RDS
        aws_metric_name: CPUUtilization
        aws_dimensions: [DBInstanceIdentifier]
        aws_statistics: [Average]
        period_seconds: 300
        range_seconds: 600
        delay_seconds: 300
        set_timestamp: true
      - aws_namespace: AWS/RDS
        aws_metric_name: DatabaseConnections
        aws_dimensions: [DBInstanceIdentifier]
        aws_statistics: [Average]
        period_seconds: 300
        range_seconds: 600
        delay_seconds: 300
        set_timestamp: true

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudwatch-exporter
  namespace: monitoring
  labels:
    app: cloudwatch-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudwatch-exporter
  template:
    metadata:
      labels:
        app: cloudwatch-exporter
    spec:
      serviceAccountName: cloudwatch-exporter
      tolerations:
      - key: "node-type"
        operator: "Equal"
        value: "monitoring"
        effect: "NoSchedule"
      containers:
      - name: cloudwatch-exporter
        image: prom/cloudwatch-exporter:latest
        args:
          - "/etc/cloudwatch_exporter/config.yml"
          - "9106"
        ports:
        - containerPort: 9106
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
        volumeMounts:
        - name: config-volume
          mountPath: /etc/cloudwatch_exporter
      volumes:
      - name: config-volume
        configMap:
          defaultMode: 420
          name: cloudwatch-exporter-config

---
apiVersion: v1
kind: Service
metadata:
  name: cloudwatch-exporter
  namespace: monitoring
  labels:
    app: cloudwatch-exporter
spec:
  selector:
    app: cloudwatch-exporter
  ports:
  - port: 9106
    targetPort: 9106
  type: ClusterIP

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloudwatch-exporter
  namespace: monitoring

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cloudwatch-exporter
rules:
- apiGroups: [""]
  resources: ["nodes", "services", "endpoints", "pods"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cloudwatch-exporter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cloudwatch-exporter
subjects:
- kind: ServiceAccount
  name: cloudwatch-exporter
  namespace: monitoring




